{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-alignment
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - scikit-bio
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*
    - mafft >=7.394
    - sina >=1.3.5,<=2

test:
  imports:
    - q2_alignment
    - qiime2.plugins.alignment

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
